Added the ability to deploy licenses

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,2 +1,30 @@
 #!/bin/bash
+
+say() {
+	echo -e "$(date -Isec): ${@}"
+}
+
+[ -v BASE_DIR ] || BASE_DIR="/app"
+[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
+
+#
+# TODO: Run initialization (i.e. put the license in the right place, etc.)
+#
+# Bootstrap info: https://docs.alfresco.com/content-services/latest/develop/repo-ext-points/bootstrap-content/
+#
+
+#
+# First things first: if there's a license in ${INIT_DIR}, apply it
+#
+[ -v LICENSE_DIR ] || LICENSE_DIR="/usr/local/tomcat/shared/classes/alfresco/extension/license"
+[ -d "${LICENSE_DIR}" ] || mkdir -p "${LICENSE_DIR}" || fail "Failed to create the license directory [${LICENSE_DIR}]"
+while read l ; do
+	TGT="${LICENSE_DIR}/${l##*/}"
+	if [ -e "${TGT}" ] ; then
+		[ -f "${TGT}" ] || fail "The object at [${TGT}] is not a file, can't continue"
+		mv -f "${TGT}" "${TGT}.bak-$(date -u +%s)" || say "WARNING: Failed to back up the license at [${TGT}] - it will be overwritten"
+	fi
+	cp -vf "${l}" "${TGT}" || fail "Failed to deploy the license from [${l}]"
+done < <(find "${INIT_DIR}/license" -mindepth 1 -maxdepth 1 -type f -name "*.lic")
+
 exec "${CATALINA_HOME}/bin/catalina.sh" run -security
